site_name: Groosha's Blog

theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  logo: assets/logo2.png
  favicon: assets/logo2.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
      blog_toc: false
      archive_name: Архив
      categories_name: Теги

nav:
  - 'Обо мне': about.md
  - index.md
  - 'Тест': test.md