name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: astral-sh/setup-uv@v5
        with:
          python-version-file: .python-version
      - run: uv sync
      - run: uv run mkdocs gh-deploy --force
